spring:
  profiles:
    active: default
  jpa:
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailId}
    password: ${mailPassword}
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

---

spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

---

spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
logging:
  level:
    root: info
---

spring:
  profiles: sandbox
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

---

spring:
  profiles: production
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true